In [1]:
import pandas as pd
import statistics as st

In [22]:
table = pd.read_csv('dataset_Facebook.csv',
                       sep=';')
titles = list(table)
titles.remove("Type")

# Создаем функцию для вычесления моды (наиболее популярное значение)
def mymode(x):
    try:
        return st.mode(x)
    except:
        return "No mode"

#Создаем 5 таблиц, в которых будут, соответственно, рассчитаны средние значения, медианы, моды, MAX и MIN 
# для каждого типа контента и для всего массива в целом в разрезе всех параметров массива.

table_mean = table.pivot_table(index = ["Type"], aggfunc = 'mean', margins = True, dropna=False).round(2)[titles]
table_median = table.pivot_table(index = ["Type"], aggfunc ='median', margins = True, dropna=False).round(2)[titles]
table_mode = table.pivot_table(index = ["Type"], aggfunc = mymode, margins = True, dropna=False).round(2)[titles]
table_max = table.pivot_table(index = ["Type"], aggfunc ='max', margins = True, dropna=False).round(2)[titles]
table_min = table.pivot_table(index = ["Type"], aggfunc ='min', margins = True, dropna=False).round(2)[titles]


# Популярность поста можно определить разными способами на основе параметров выгрузки.
# Основным параметром, который определяет интерес людей к посту является коэффициент вовлеченности.
# Вовлеченность - это доля людей, которые кликнули на пост (CTR_Eng).
# С другой стороны, важно еще абсолютное значение вовлеченных людей.
# Например, если пост увидели и кликнули всего 10 человек, то CTR_Eng = 1.
# Но такой пост нельзя назвать популярным.
# Поэтому введем такой параметр как Part_Eng. Будем ее считать как отношение кол-ва вовлеченных людей
# к максимальному кол-ву вовлеченных людей в выборке (получаем нормированную величину).
# Критерий популярности определим как сумму коэффициенто CTR_Eng + Part_Eng.
# Будем считать, что Part_Eng несколько важнее чем Part_Eng.
# Чем больше людей просмотрело пост, тем он более популярен.
# Будем использовать веса P1 и P2 для параметров CTR_Eng и Part_Eng.
# Для задачи возьмем веса P1 = 0.4, P2 = 0.6 (их можно варьировать).

table["CTR_Eng"] = (table["Lifetime Engaged Users"]/table["Lifetime Post Total Reach"]).round(2)
table["Part_Eng"] = (table["Lifetime Engaged Users"]/table["Lifetime Engaged Users"].max()).round(2)
P1 = 0.4
P2 = 0.6
table["CTR_Val"] = P1 * table["CTR_Eng"] + P2 * table["Part_Eng"]


# Сортировка таблицы по убыванию значения параметра CTR_Val
table.sort_values(by = "CTR_Val", ascending = False, inplace = True) 
table["RN"] = range(1, len(table.index)+1)


# Вывод ТОП N наиболее популярных публикаций. Значение TOP можно задать ниже (по умолчанию ТОП = 1).
TOP = 1
table.loc[table["RN"].isin([x for x in range(TOP+1)])]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,...,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions,CTR_Eng,Part_Eng,CTR_Val,RN
446,96749,Photo,1,3,1,2,1.0,98816,125026,11452,...,10336,1356,10,197.0,21.0,228,0.12,1.0,0.648,1

In [23]:
table_mean

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
Type,,,,,,,,,,,,,,,,,,
Link,116363.18,1.14,6.59,4.27,5.73,0.27,18544.59,28725.45,342.82,292.68,374.09,11148.59,6544.36,210.55,2.82,73.32,12.91,89.05
Photo,122354.17,1.92,6.81,4.11,8.00,0.28,13137.81,28994.50,818.95,690.43,1299.03,16422.48,6059.10,507.31,7.49,182.61,27.16,216.58
Status,132647.04,2.02,9.07,4.58,7.24,0.22,13078.89,24244.47,2040.22,1949.56,2838.87,18664.27,9908.58,1719.84,8.91,176.71,31.42,217.04
Video,135014.86,1.00,9.57,3.57,8.71,0.57,51205.71,102622.43,1707.00,1584.71,2600.14,43149.86,17386.29,979.43,12.29,231.43,52.14,295.86
All,123194.18,1.88,7.04,4.15,7.84,0.28,13903.36,29585.95,920.34,798.77,1415.13,16766.38,6585.49,609.99,7.48,177.95,27.27,212.12

In [24]:
table_median

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
Type,,,,,,,,,,,,,,,,,,
Link,115396.0,1.0,4.5,4.5,4.0,0.0,7422.0,9773.0,244.0,205.0,290.0,9034.5,5039.0,161.5,1.5,37.0,10.5,52.5
Photo,128032.0,2.0,7.0,4.0,9.0,0.0,4675.0,8118.5,605.5,528.5,827.0,5498.0,3110.0,403.0,3.0,100.0,19.0,122.0
Status,135713.0,2.0,10.0,5.0,9.0,0.0,11096.0,20849.0,1701.0,1599.0,2201.0,17502.0,8980.0,1604.0,4.0,150.0,28.0,186.0
Video,137893.0,1.0,11.0,3.0,11.0,1.0,30624.0,56950.0,1779.0,1643.0,2331.0,30131.0,14112.0,885.0,17.0,204.0,44.0,271.0
All,129600.0,2.0,7.0,4.0,9.0,0.0,5281.0,9051.0,625.5,551.5,851.0,6255.5,3417.0,412.0,3.0,101.0,19.0,123.5

In [25]:
table_mode

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
Type,,,,,,,,,,,,,,,,,,
Link,138353,1,12,6,3,0.0,No mode,No mode,66,322,No mode,No mode,No mode,No mode,0,No mode,2,14
Photo,124940,1,10,7,3,0.0,No mode,No mode,537,No mode,No mode,No mode,No mode,403,0,No mode,14,No mode
Status,139441,2,12,No mode,10,0.0,No mode,No mode,No mode,No mode,1692,No mode,No mode,No mode,No mode,No mode,No mode,No mode
Video,137893,1,11,No mode,11,1.0,No mode,No mode,No mode,No mode,No mode,No mode,No mode,No mode,No mode,No mode,13,No mode
All,136393,1,10,7,3,0.0,No mode,No mode,537,No mode,No mode,No mode,No mode,403,0,98,No mode,No mode

In [26]:
table_max

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
Type,,,,,,,,,,,,,,,,,,
Link,138895,3,12,7,14,1.0,70912,229733,1374,1106,1345,42338,27232,788,15,379.0,44.0,420
Photo,139441,3,12,7,23,1.0,180480,1110282,11452,11328,19779,1107833,51456,3430,372,5172.0,790.0,6334
Status,139441,3,12,7,15,1.0,31136,59964,6164,5934,9237,37849,21352,4376,60,859.0,123.0,1009
Video,138895,1,12,6,13,1.0,139008,277100,3872,3822,7327,107502,38720,2218,23,449.0,121.0,550
All,139441,3,12,7,23,1.0,180480,1110282,11452,11328,19779,1107833,51456,4376,372,5172.0,790.0,6334

In [21]:
table_min

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
Type,,,,,,,,,,,,,,,,,,
Link,85979,1,1,1,2,0.0,1536,3094,24,23,26,2307,1180,19,0,5.0,0.0,6
Photo,81370,1,1,1,1,0.0,238,570,9,9,9,567,236,9,0,0.0,0.0,0
Status,104070,1,3,1,2,0.0,3930,7509,128,86,112,5009,2410,101,0,13.0,1.0,17
Video,126424,1,6,2,2,0.0,13544,30235,459,411,539,21436,9568,363,2,65.0,13.0,81
All,81370,1,1,1,1,0.0,238,570,9,9,9,567,236,9,0,0.0,0.0,0